### ISSUE TITLE
Post to Atom Themes

### ISSUE THREAD

**Issue by ebramanti** [AuthorOfTheSurf/hyrule-atom#7]
I would love to use your theme, but it's not yet available publically. It would be cool if you could post it to Atom's theme packages repo.

If it's still WIP, it would be great if you could add a guide to the README on how to install a development version.

**Comment by AuthorOfTheSurf** [comment]
I pushed an update to the readme, report back if the instructions work for you :grin:

**Comment by ebramanti** [comment]
:+1:
